name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: build wasm-pack
        run: wasm-pack build --release
      - name: change www dir
        run: cd www
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist